baseURL = "https://logmate.co.nz/"
languageCode = "en-us"
title = "logmate"
theme = "logmate"

[params]
description = "a truly mobile work-time compliance platform for the new zealand transportation industry"