baseURL = "https://logmate.co.nz/"
languageCode = "en-us"
title = "logmate"
theme = "logmate"

[params]
description = "a truly mobile work-time compliance platform for the new zealand transportation industry"

[module]
    [[module.mounts]]
        source = "content"
        target = "content"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "layouts"
        target = "layouts"

    [[module.mounts]]
        source = "data"
        target = "data"

    [[module.mounts]]
        source = "layouts"
        target = "layouts"

    [[module.mounts]]
        source = "archetypes"
        target = "archetypes"