[build]
publish = "public"
command = "npm --prefix themes/logmate/ i && hugo"

[[redirects]]
    from = "https://logmate.netlify.com/*"
    to = "https://logmate.co.nz/:splat"
    status = 301

[[redirects]]
    from = "/drivers"
    to = "/products/drivers-logbook/"
    status = 301

[[redirects]]
    from = "/media"
    to = "/"
    status = 301

[[redirects]]
    from = "/terms"
    to = "/policies/terms/"
    status = 301

[[redirects]]
    from = "/privacy.html"
    to = "/policies/privacy/"
    status = 301

[[redirects]]
    from = "/mobile.html"
    to = "/policies/mobile/"
    status = 301

[[redirects]]
    from = "/about.html"
    to = "/about/company/"
    status = 301