---
label: Blog post
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: title
  description: title of article used in nav and at top of document
- name: description
  type: text
  config:
    required: false
  label: description
  description: Description of article which is used in meta data
- name: keywords
  type: tag_list
  default: []
  label: keywords
  description: article keywords used as tags and meta data
- name: author
  type: text
  config:
    required: false
  label: author
  description: name of article author
