---
label: Blog post
hide_body: false
fields:
- name: article_title
  type: text
  config:
    required: false
  label: Article title
- name: article_body
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Article body
